### ISSUE TITLE
Peak finding bug

### ISSUE THREAD

**Issue by emirkmo** [temuller/piscola#3] opened 2022-08-23 14:42 UTC
https://github.com/temuller/piscola/blob/f4f6116bffe3578ba005a8dedb4e9eb353f17e9e/src/piscola/sn_class.py#L252

if peak is first point or before, fails, should warn but maybe use max as peak?

Or extrapolate longer when it fails? If slope is steep no peak.

> SN2011jt failed:index 0 is out of bounds for axis 0 with size 0

**Comment by temuller** [comment] 2022-08-29 14:16
This is usually caused caused by not have data around and before B-band peak. As a reminder, the peak is wherever the derivative is zero. I have fixed this ([see commit](https://github.com/temuller/piscola/commit/df91ab071427d68f2ab58a9fcd72ee8a18c0c6eb)). PISCOLA now further extrapolates back (not forward!) in the time axis until a peak can be found. I do not just pick the max value as I trust the extrapolation more than the former. However, this means that the peak might be far from the observations, but the uncertainties in the fits should reflect this and somewhat compensate for this fact. Anyway, I believe that the current solution should work in pretty much all cases with this issue, so I will close it. Thanks!

**Closed as completed by temuller** 2022-08-29 14:16 UTC
